title: "Mk personal webpage"
author: "Kudzaishe Mwaza"
baseurl: ""
url: "https://mwazakd.github.io"
exclude:
  - DEPLOYMENT_GUIDE.md
  - SETUP_INSTRUCTIONS.md
  - setup.bat
  - README.md
  - node_modules
  - _site
  - .github
  - package-lock.json
  - package.json
  - Gemfile
  - Gemfile.lock